#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("tapthemole2.Resource", IsApplication=true)]

namespace tapthemole2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::tapthemole2.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::tapthemole2.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::tapthemole2.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::tapthemole2.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::tapthemole2.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::tapthemole2.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::tapthemole2.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::tapthemole2.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::tapthemole2.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::tapthemole2.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::tapthemole2.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::tapthemole2.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::tapthemole2.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::tapthemole2.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::tapthemole2.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::tapthemole2.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::tapthemole2.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::tapthemole2.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::tapthemole2.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::tapthemole2.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::tapthemole2.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::tapthemole2.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alternativemoleholes = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bomba1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bomba2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bomba3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bomba4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int flechaatras = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int fondo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int hole = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int logoclick = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int mole = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int molealt = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int moleholes = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int start = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050018
			public const int OptionHostName = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int OptionPort = 2131034137;
			
			// aapt resource value: 0x7f050017
			public const int OptionRemoteServer = 2131034135;
			
			// aapt resource value: 0x7f050027
			public const int OptionsButton = 2131034151;
			
			// aapt resource value: 0x7f050022
			public const int ResultFullName = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int ResultMessage = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int ResultResultState = 2131034147;
			
			// aapt resource value: 0x7f050021
			public const int ResultRunSingleMethodTest = 2131034145;
			
			// aapt resource value: 0x7f050025
			public const int ResultStackTrace = 2131034149;
			
			// aapt resource value: 0x7f05001d
			public const int ResultsFailed = 2131034141;
			
			// aapt resource value: 0x7f05001a
			public const int ResultsId = 2131034138;
			
			// aapt resource value: 0x7f05001e
			public const int ResultsIgnored = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int ResultsInconclusive = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int ResultsMessage = 2131034144;
			
			// aapt resource value: 0x7f05001c
			public const int ResultsPassed = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int ResultsResult = 2131034139;
			
			// aapt resource value: 0x7f050026
			public const int RunTestsButton = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int TestSuiteListView = 2131034152;
			
			// aapt resource value: 0x7f050009
			public const int bomba1 = 2131034121;
			
			// aapt resource value: 0x7f050012
			public const int bomba10 = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int bomba2 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int bomba3 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int bomba4 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int bomba5 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int bomba6 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int bomba7 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int bomba8 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int bomba9 = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int crono = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int crono_text = 2131034133;
			
			// aapt resource value: 0x7f050008
			public const int flechatras = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int mole_move = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int myButton = 2131034119;
			
			// aapt resource value: 0x7f050016
			public const int n_highscore = 2131034134;
			
			// aapt resource value: 0x7f050003
			public const int principal = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int score = 2131034114;
			
			// aapt resource value: 0x7f050013
			public const int start = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int tableLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int tableRow1 = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int time = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int time_over = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int options = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int results = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int test_result = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int test_suite = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
